extends Node

var currentUnit = "Imperial Swordsman"
var currentEnemyUnit = "Imperial Swordsman"
var mana = 50
var maxMana = 100
var enemyMana = 10
var enemyMaxMana = 50
var onUI = false

var minutes = 2
var seconds = 59
var generalHealth = 2000
var enemyGeneralHealth = 2000
var descOpen = false
var unitList = ["Imperial Officer","Imperial Swordsman", "Imperial Musketeer", "Imperial Sergeant", "Imperial Rifleman", "Imperial Sapper","Imperial Hussar", "Imperial Lancer", "Imperial Dragoon","Imperial Cannon"]
var enemyUnitList = ["Imperial Officer","Imperial Swordsman", "Imperial Musketeer", "Imperial Sergeant", "Imperial Rifleman", "Imperial Sapper","Imperial Hussar", "Imperial Lancer", "Imperial Dragoon","Imperial Cannon"]
var gamemode = "Clash"

var unitDict = {
	"Imperial Swordsman": {
		"cost": 10,
		"maxHp": 110,
		"maxMorale": 60,
		"unitName": "Imperial Swordsman",
		"maxSpeed": 300,
		"size": 1.0,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/imperialSwordsman (2).png"),
		"damage": 10,
		"attackSpeed": 250,
		"meleeWeaponReach": 1.2,
		"thrustAmplitude": 50,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": [],
		"conditions": [],
		"desc": "A Imperial army private, straight from boot camp. He is cheap, fast, and wields an infantry sword."
	},
	"Imperial Musketeer": {
		"cost": 15,
		"maxHp": 80,
		"maxMorale": 40,
		"unitName": "Imperial Musketeer",
		"maxSpeed": 180,
		"size": 1.0,
		"icon": preload("res://Assets/imperialMusketeerIcon.png"),
		"sprite": preload("res://Assets/imperialMusketeer.png"),
		"damage": 5,
		"attackSpeed": 8000,
		"meleeWeaponReach": 0.5,
		"thrustAmplitude": 30,
		"rangedDamage": 80,
		"projectileSpeed": 3500,
		"projectileLife": 3,
		"rangeRadius": 750.0,
		"rateOfFire": 10,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Skirmish","Gun"],
		"conditions": [],
		"desc": "An imperial soldier with a powerful musket that can pierce shields. However, it takes a long time to reload."
	},
	"Imperial Sergeant": {
		"cost": 25,
		"maxHp": 130,
		"maxMorale": 70,
		"unitName": "Imperial Sergeant",
		"maxSpeed": 210,
		"size": 1.1,
		"icon": preload("res://Assets/imperialSergeantIcon.png"),
		"sprite": preload("res://Assets/imperialSergeant.png"),
		"damage": 25,
		"attackSpeed": 4,
		"meleeWeaponReach": 0.5,
		"thrustAmplitude": 35,
		"rangedDamage": 50,
		"projectileSpeed": 3000,
		"projectileLife": 3,
		"rangeRadius": 500.0,
		"rateOfFire": 15,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Morale Aura", "Thrust","Gun"],
		"conditions": [],
		"desc": "An experienced soldier with a musket, bayonet, and an inflated ego. He gives morale to units beside him."
	},
	"Imperial Officer": {
		"cost": 35,
		"maxHp": 120,
		"maxMorale": 90,
		"unitName": "Imperial Officer",
		"maxSpeed": 220,
		"size": 1.1,
		"icon": preload("res://Assets/imperialOfficerIcon.png"),
		"sprite": preload("res://Assets/imperialOfficer.png"),
		"damage": 15,
		"attackSpeed": 400,
		"meleeWeaponReach": 1.3,
		"thrustAmplitude": 60,
		"rangedDamage": 50,
		"projectileSpeed": 1300,
		"projectileLife": 3.5,
		"rangeRadius": 300,
		"rateOfFire": 10,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Morale Aura", "Gun"],
		"conditions": [],
		"desc": "A high-ranking imperial commander who inspires nearby troops with his presence. He wields both a ceremonial sword and a refined pistol."
	},
	"Imperial Rifleman": {
		"cost": 18,
		"maxHp": 85,
		"maxMorale": 45,
		"unitName": "Imperial Rifleman",
		"maxSpeed": 190,
		"size": 1.0,
		"icon": preload("res://Assets/imperialRiflemanIcon (1).png"),
		"sprite": preload("res://Assets/imperialRifleman.png"),
		"damage": 6,
		"attackSpeed": 5000,
		"meleeWeaponReach": 0.8,
		"thrustAmplitude": 40,
		"rangedDamage": 100,
		"projectileSpeed": 4000,
		"projectileLife": 3,
		"rangeRadius": 1000.0,
		"rateOfFire": 20,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Skirmish", "Gun"],
		"conditions": [],
		"desc": "An elite marksman equipped with a precision rifle for long-range engagements. His shots are deadly accurate but require careful positioning."
	},
	"Imperial Sapper": {
		"cost": 20,
		"maxHp": 60,
		"maxMorale": 35,
		"unitName": "Imperial Sapper",
		"maxSpeed": 130,
		"size": 1.0,
		"icon": preload("res://Assets/imperialSapperIcon.png"),
		"sprite": preload("res://Assets/imperialSapper.png"),
		"damage": 20,
		"attackSpeed": 100,
		"meleeWeaponReach": 1,
		"thrustAmplitude": 35,
		"rangedDamage": 10,
		"projectileSpeed": 500,
		"projectileLife": 2.5,
		"rangeRadius": 100.0,
		"rateOfFire": 30,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Fireball"],
		"conditions": [],
		"desc": "A demolitions expert who uses grenades and a big axe to destroy structures. His grenades can devastate clustered enemies but have limited range."
	},
	"Imperial Hussar": {
		"cost": 28,
		"maxHp": 110,
		"maxMorale": 60,
		"unitName": "Imperial Hussar",
		"maxSpeed": 500,
		"size": 1.1,
		"icon": preload("res://Assets/imperialHussarIcon.png"),
		"sprite": preload("res://Assets/imperialHussar.png"),
		"damage": 12,
		"attackSpeed": 200,
		"meleeWeaponReach": 1.0,
		"thrustAmplitude": 55,
		"rangedDamage": 20,
		"projectileSpeed": 1100,
		"projectileLife": 2,
		"rangeRadius": 450.0,
		"rateOfFire": 4,
		"isMelee": true,
		"isRanged": false,
		"skills": [],
		"conditions": [],
		"desc": "A fast-moving rider armed with a cavalry saber. He excels at harassment and can be summoned on the flanks."
	},
	"Imperial Lancer": {
		"cost": 38,
		"maxHp": 130,
		"maxMorale": 65,
		"unitName": "Imperial Lancer",
		"maxSpeed": 480,
		"size": 1.1,
		"icon": preload("res://Assets/imperialLancerIcon.png"),
		"sprite": preload("res://Assets/imperialLancer.png"),
		"damage": 40,
		"attackSpeed": 5,
		"meleeWeaponReach": 2.5,
		"thrustAmplitude": 80,
		"rangedDamage": 0,
		"projectileSpeed": 0,
		"projectileLife": 0,
		"rangeRadius": 0.0,
		"rateOfFire": 0.0,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Thrust", "Charge"],
		"conditions": [],
		"desc": "A heavy cavalry soldier wielding a long lance for devastating charges. His momentum can pierce through multiple enemies in a single attack."
	},
	"Imperial Dragoon": {
		"cost": 32,
		"maxHp": 125,
		"maxMorale": 70,
		"unitName": "Imperial Dragoon",
		"maxSpeed": 400,
		"size": 1.1,
		"icon": preload("res://Assets/imperialDragoonIcon.png"),
		"sprite": preload("res://Assets/imperialDragoon.png"),
		"damage": 16,
		"attackSpeed": 6000,
		"meleeWeaponReach": 1.1,
		"thrustAmplitude": 65,
		"rangedDamage": 40,
		"projectileSpeed": 1400,
		"projectileLife": 3,
		"rangeRadius": 300.0,
		"rateOfFire": 1.5,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Skirmish", "Gun"],
		"conditions": [],
		"desc": "An elite mounted soldier who uses a cavalry carbine. He is very good at skirmishing."
	},
	"Imperial Cannon": {
		"cost": 40,
		"maxHp": 30,
		"maxMorale": 100,
		"unitName": "Imperial Cannon",
		"maxSpeed": 10,
		"size": 1.2,
		"icon": preload("res://Assets/imperialCannonerIcon.png"),
		"sprite": preload("res://Assets/imperialCannon.png"),
		"damage": 5,
		"attackSpeed": 15000,
		"meleeWeaponReach": 0.5,
		"thrustAmplitude": 20,
		"rangedDamage": 80,
		"projectileSpeed": 6800,
		"projectileLife": 5,
		"rangeRadius": 1500.0,
		"rateOfFire": 15,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Fireball", "Cannon"],
		"conditions": [],
		"desc": "A massive artillery piece that can devastate enemy formations from extreme range. It requires time to reload but delivers crushing explosive damage."
	},
	"Goblin": {
		"cost": 5,
		"maxHp": 60,
		"maxMorale": 30,
		"unitName": "Goblin",
		"maxSpeed": 230,
		"size": 0.8,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/goblinDagger.png"),
		"damage": 5,
		"attackSpeed": 50,
		"meleeWeaponReach": 0.8,
		"thrustAmplitude": 25,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Thrust"],
		"conditions": [],
		"desc": "A small green monster who works for the necromancer as a slave-soldier. He is fast, but weak and cowardly."
	}
}
func _ready() -> void:
	while true:
		enemyMana += 1
		mana += 1
		await get_tree().create_timer(0.1).timeout
		
func _process(delta: float) -> void:
	mana = clamp(mana, 0, maxMana)
	enemyMana = clamp(enemyMana, 0, enemyMaxMana)
	
