extends Node

var currentUnit = "Imperial Swordsman"
var currentEnemyUnit = "Imperial Swordsman"
var currentDescUnit = "Imperial Swordsman"
var currentDescUnit2 = "Barbados"
var replacingUnit = ""
var mana = 50
var maxMana = 300
var enemyMana = 100
var enemyMaxMana = 500
var onUI = false
var paused = false
var replacing = false
var heroPlaced = false
var enemyHeroPlaced = false

var minutes = 2
var seconds = 59
var generalHealth = 2000
var enemyGeneralHealth = 2000
var descOpen = false
var desc2Open = false
var unitList = ["Imperial Officer","Imperial Swordsman", "Imperial Musketeer", "Imperial Sergeant", "Imperial Rifleman", "Ludwig","Imperial Hussar", "Imperial Lancer", "Imperial Dragoon","Imperial Cannon"]
var enemyUnitList = ["Goblin","Spear Goblin", "Dart Goblin", "Orc", "Hobgoblin", "Ogre","Goblin","Spear Goblin", "Stone Giant", "Orc"]
var inventory = ["Barbados","Blorzik","Imperial Sapper"]
var gamemode = "Clash"


	
var unitDict = {
	"Imperial Swordsman": {
		"cost": 10,
		"maxHp": 110,
		"maxMorale": 60,
		"unitName": "Imperial Swordsman",
		"maxSpeed": 240,
		"size": 1.0,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/imperialSwordsman (2).png"),
		"damage": 10,
		"attackSpeed": 250,
		"meleeWeaponReach": 1.2,
		"thrustAmplitude": 50,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": [],
		
		"desc": "A Imperial army private, straight from boot camp. He is cheap, fast, and wields an infantry sword."
	},
	"Imperial Musketeer": {
		"cost": 15,
		"maxHp": 80,
		"maxMorale": 50,
		"unitName": "Imperial Musketeer",
		"maxSpeed": 180,
		"size": 1.0,
		"icon": preload("res://Assets/imperialMusketeerIcon.png"),
		"sprite": preload("res://Assets/imperialMusketeer.png"),
		"damage": 5,
		"attackSpeed": 8000,
		"meleeWeaponReach": 0.5,
		"thrustAmplitude": 30,
		"rangedDamage": 80,
		"projectileSpeed": 3500,
		"projectileLife": 0.9,
		"rangeRadius": 750.0,
		"rateOfFire": 10,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Skirmish","Gun"],
		
		"desc": "An imperial soldier with a powerful musket that can pierce shields. However, it takes a long time to reload."
	},
	"Imperial Sergeant": {
		"cost": 25,
		"maxHp": 130,
		"maxMorale": 70,
		"unitName": "Imperial Sergeant",
		"maxSpeed": 210,
		"size": 1.1,
		"icon": preload("res://Assets/imperialSergeantIcon.png"),
		"sprite": preload("res://Assets/imperialSergeant.png"),
		"damage": 25,
		"attackSpeed": 4,
		"meleeWeaponReach": 0.5,
		"thrustAmplitude": 35,
		"rangedDamage": 50,
		"projectileSpeed": 3000,
		"projectileLife": 0.75,
		"rangeRadius": 500.0,
		"rateOfFire": 15,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Thrust","Gun"],
		
		"desc": "An experienced soldier with a musket, bayonet, and an inflated ego. He can shoot while advancing."
	},
	"Imperial Officer": {
		"cost": 35,
		"maxHp": 150,
		"maxMorale": 90,
		"unitName": "Imperial Officer",
		"maxSpeed": 220,
		"size": 1.1,
		"icon": preload("res://Assets/imperialOfficerIcon.png"),
		"sprite": preload("res://Assets/imperialOfficer.png"),
		"damage": 15,
		"attackSpeed": 500,
		"meleeWeaponReach": 1.3,
		"thrustAmplitude": 60,
		"rangedDamage": 50,
		"projectileSpeed": 1300,
		"projectileLife": 0.5,
		"rangeRadius": 300,
		"rateOfFire": 10,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Morale Aura", "Gun"],
		
		"desc": "A high-ranking imperial commander who inspires nearby troops with his presence. He wields both a ceremonial sword and a refined pistol."
	},
	"Imperial Rifleman": {
		"cost": 18,
		"maxHp": 65,
		"maxMorale": 45,
		"unitName": "Imperial Rifleman",
		"maxSpeed": 250,
		"size": 1.0,
		"icon": preload("res://Assets/imperialRiflemanIcon (1).png"),
		"sprite": preload("res://Assets/imperialRifleman.png"),
		"damage": 6,
		"attackSpeed": 5000,
		"meleeWeaponReach": 0.8,
		"thrustAmplitude": 40,
		"rangedDamage": 120,
		"projectileSpeed": 3000,
		"projectileLife": 1.5,
		"rangeRadius": 1200.0,
		"rateOfFire": 20,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Skirmish", "Gun"],
		
		"desc": "An elite marksman equipped with a precision rifle for long-range engagements. His shots are deadly accurate but require careful positioning."
	},
	"Imperial Sapper": {
		"cost": 20,
		"maxHp": 60,
		"maxMorale": 35,
		"unitName": "Imperial Sapper",
		"maxSpeed": 130,
		"size": 1.0,
		"icon": preload("res://Assets/imperialSapperIcon.png"),
		"sprite": preload("res://Assets/imperialSapper.png"),
		"damage": 20,
		"attackSpeed": 100,
		"meleeWeaponReach": 1,
		"thrustAmplitude": 35,
		"rangedDamage": 10,
		"projectileSpeed": 500,
		"projectileLife": 1,
		"rangeRadius": 100.0,
		"rateOfFire": 30,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Fireball"],
		
		"desc": "A demolitions expert who uses grenades and a big axe to destroy structures. His grenades can devastate clustered enemies but have limited range."
	},
	"Imperial Hussar": {
		"cost": 28,
		"maxHp": 170,
		"maxMorale": 60,
		"unitName": "Imperial Hussar",
		"maxSpeed": 550,
		"size": 1.1,
		"icon": preload("res://Assets/imperialHussarIcon.png"),
		"sprite": preload("res://Assets/imperialHussar.png"),
		"damage": 12,
		"attackSpeed": 600,
		"meleeWeaponReach": 2.0,
		"thrustAmplitude": 55,
		"rangedDamage": 20,
		"projectileSpeed": 1100,
		"projectileLife": 2,
		"rangeRadius": 450.0,
		"rateOfFire": 4,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Flank"],
		
		"desc": "A fast-moving rider armed with a cavalry saber. He excels at speed and can be summoned on the flanks."
	},
	"Imperial Lancer": {
		"cost": 38,
		"maxHp": 195,
		"maxMorale": 65,
		"unitName": "Imperial Lancer",
		"maxSpeed": 510,
		"size": 1.1,
		"icon": preload("res://Assets/imperialLancerIcon.png"),
		"sprite": preload("res://Assets/imperialLancer.png"),
		"damage": 50,
		"attackSpeed": 1.5,
		"meleeWeaponReach": 0.5,
		"thrustAmplitude": 80,
		"rangedDamage": 0,
		"projectileSpeed": 0,
		"projectileLife": 0,
		"rangeRadius": 0.0,
		"rateOfFire": 0.0,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Thrust", "Charge"],
		
		"desc": "A heavy cavalry soldier wielding a long lance for devastating charges. His momentum can pierce through multiple enemies in a single attack."
	},
	"Imperial Dragoon": {
		"cost": 32,
		"maxHp": 145,
		"maxMorale": 70,
		"unitName": "Imperial Dragoon",
		"maxSpeed": 530,
		"size": 1.1,
		"icon": preload("res://Assets/imperialDragoonIcon.png"),
		"sprite": preload("res://Assets/imperialDragoon.png"),
		"damage": 16,
		"attackSpeed": 6000,
		"meleeWeaponReach": 1.1,
		"thrustAmplitude": 65,
		"rangedDamage": 40,
		"projectileSpeed": 2400,
		"projectileLife": 0.75,
		"rangeRadius": 350.0,
		"rateOfFire": 2,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Skirmish", "Gun"],
		
		"desc": "An elite mounted soldier who uses a cavalry carbine. He is very good at skirmishing."
	},
	"Imperial Cannon": {
		"cost": 40,
		"maxHp": 30,
		"maxMorale": 100,
		"unitName": "Imperial Cannon",
		"maxSpeed": 10,
		"size": 1.2,
		"icon": preload("res://Assets/imperialCannonerIcon.png"),
		"sprite": preload("res://Assets/imperialCannon.png"),
		"damage": 5,
		"attackSpeed": 15000,
		"meleeWeaponReach": 0.5,
		"thrustAmplitude": 20,
		"rangedDamage": 300,
		"projectileSpeed": 2500,
		"projectileLife": 1.1,
		"rangeRadius": 2100.0,
		"rateOfFire": 20,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Fireball", "Cannon"],
		
		"desc": "A massive artillery piece that can devastate enemy formations from extreme range. It is very slow but delivers crushing explosive damage."
	},
	"Goblin": {
		"cost": 5,
		"maxHp": 60,
		"maxMorale": 30,
		"unitName": "Goblin",
		"maxSpeed": 230,
		"size": 0.8,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/goblinDagger.png"),
		"damage": 5,
		"attackSpeed": 50,
		"meleeWeaponReach": 0.8,
		"thrustAmplitude": 25,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 600.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Thrust"],
		
		"desc": "A small green monster who works for the necromancer as a slave-soldier. He is fast, but weak and cowardly."
	},
	"Spear Goblin": {
		"cost": 7,
		"maxHp": 35,
		"maxMorale": 20,
		"unitName": "Spear Goblin",
		"maxSpeed": 230,
		"size": 0.8,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/spearGoblin.png"),
		"damage": 10,
		"attackSpeed": 20,
		"meleeWeaponReach": 0.8,
		"thrustAmplitude": 25,
		"rangedDamage": 20,
		"projectileSpeed": 800,
		"projectileLife": 1,
		"rangeRadius": 500.0,
		"rateOfFire": 1.5,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Thrust"],
		
		"desc": "A goblin with throwing spears. He throws them, and uses them in melee."
	},
	"Dart Goblin": {
		"cost": 15,
		"maxHp": 30,
		"maxMorale": 35,
		"unitName": "Dart Goblin",
		"maxSpeed": 230,
		"size": 0.8,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/dartGoggins.png"),
		"damage": 5,
		"attackSpeed": 10,
		"meleeWeaponReach": 0.8,
		"thrustAmplitude": 25,
		"rangedDamage": 10,
		"projectileSpeed": 600,
		"projectileLife": 1,
		"rangeRadius": 600.0,
		"rateOfFire": 1,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Skirmish"],
		"desc": "A goblin with a piece of bamboo in his long nose. He blows out poisonous darts."
	},
	"Orc": {
		"cost": 20,
		"maxHp": 120,
		"maxMorale": 60,
		"unitName": "Orc",
		"maxSpeed": 180,
		"size": 1.1,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/orc.png"),
		"damage": 20,
		"attackSpeed": 180,
		"meleeWeaponReach": 1,
		"thrustAmplitude": 25,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": [],
		"desc": "A big pig-faced brute who was hired by the necromancer. He is strong but slow."
	},
	"Hobgoblin": {
		"cost": 25,
		"maxHp": 150,
		"maxMorale": 100,
		"unitName": "Hobgoblin",
		"maxSpeed": 200,
		"size": 1.0,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/hobgoblin.png"),
		"damage": 30,
		"attackSpeed": 170,
		"meleeWeaponReach": 1,
		"thrustAmplitude": 25,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Morale Aura"],
		"desc": "A goblin officer who is respected in the Goblin army. He wears heavy armor."
	},
	"Ogre": {
		"cost": 60,
		"maxHp": 250,
		"maxMorale": 80,
		"unitName": "Ogre",
		"maxSpeed": 100,
		"size": 1.5,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/ogre.png"),
		"damage": 80,
		"attackSpeed": 110,
		"meleeWeaponReach": 1,
		"thrustAmplitude": 25,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": [],
		"desc": "A gigantic monster with a small head. He uses his club to take out swarms of enemies."
	},
	"Stone Giant": {
		"cost": 90,
		"maxHp": 200,
		"maxMorale": 80,
		"unitName": "Stone Giant",
		"maxSpeed": 80,
		"size": 1.6,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/stoneGiant.png"),
		"damage": 30,
		"attackSpeed": 50,
		"meleeWeaponReach": 1,
		"thrustAmplitude": 25,
		"rangedDamage": 100,
		"projectileSpeed": 100,
		"projectileLife": 1,
		"rangeRadius": 500.0,
		"rateOfFire": 2,
		"isMelee": false,
		"isRanged": true,
		"skills": ["Stone"],
		"desc": "A gray, stone wielding giant who is from the underground. The corrupted dwarves known as the Duergar worship these giants."
	},
	"Ludwig": {
		"cost": 200,
		"maxHp": 300,
		"maxMorale": 150,
		"unitName": "Ludwig",
		"maxSpeed": 300,
		"size": 1.0,
		"icon": preload("res://Assets/ludwigIcon.png"),
		"sprite": preload("res://Assets/ludwig.png"),
		"damage": 15,
		"attackSpeed": 200,
		"meleeWeaponReach": 1,
		"thrustAmplitude": 40,
		"rangedDamage": 120,
		"projectileSpeed": 3500,
		"projectileLife": 3,
		"rangeRadius": 800.0,
		"rateOfFire": 3,
		"isMelee": true,
		"isRanged": true,
		"skills": ["Skirmish", "Gun", "Flashbang", "Hero"],
		"desc": "A mysterious arcane sniper who used to be an imperial soldier and now works as a monster hunter. He uses a magic musket and flashbangs that stun enemies"
	},
	"Barbados": {
		"cost": 250,
		"maxHp": 500,
		"maxMorale": 200,
		"unitName": "Barbados",
		"maxSpeed": 330,
		"size": 1.1,
		"icon": preload("res://Assets/barbadosIcon.png"),
		"sprite": preload("res://Assets/barbados.png"),
		"damage": 60,
		"attackSpeed": 250,
		"meleeWeaponReach": 1.2,
		"thrustAmplitude": 50,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Werewolf", "Hero"],
		"desc": "A powerful swordsman with otherworldly armor. When he runs out of HP, he activates his alpha werewolf form."
	},
	"Alpha Barbados": {
		"cost": 10,
		"maxHp": 1000,
		"maxMorale": 350,
		"unitName": "Alpha Barbados",
		"maxSpeed": 540,
		"size": 1.5,
		"icon": preload("res://Assets/imperialSwordsmanIcon.png"),
		"sprite": preload("res://Assets/werewolf.png"),
		"damage": 20,
		"attackSpeed": 5500,
		"meleeWeaponReach": 1.4,
		"thrustAmplitude": 50,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 500.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Hero"],
		"desc": "IMA RIP AND TEAR."
	},
	"Blorzik": {
		"cost": 180,
		"maxHp": 900,
		"maxMorale": 220,
		"unitName": "Blorzik",
		"maxSpeed": 600,
		"size": 0.8,
		"icon": preload("res://Assets/blorzikIcon.png"),
		"sprite": preload("res://Assets/blorzik.png"),
		"damage": 15,
		"attackSpeed": 5000,
		"meleeWeaponReach": 0.8,
		"thrustAmplitude": 25,
		"rangedDamage": 20,
		"projectileSpeed": 1000,
		"projectileLife": 2,
		"rangeRadius": 600.0,
		"rateOfFire": 0.5,
		"isMelee": true,
		"isRanged": false,
		"skills": ["Thrust", "Fear Aura", "Hero"],
		"desc": "An insane gnome who has a deep lust for blood. He murdered 3/4s of the population of his hometown, Gimmelstump. His aura causes morale loss amongst enemies."
	}
}

func _ready() -> void:
	
	while true:
		enemyMana += 2
		mana += 2
		await get_tree().create_timer(0.1).timeout
		
func _process(delta: float) -> void:
	mana = clamp(mana, 0, maxMana)
	enemyMana = clamp(enemyMana, 0, enemyMaxMana)
